name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Configure
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug
    - name: Build
      run: |
        cmake --build build --config Debug
    - name: Test
      run: |
        cp -r test data ./build
        cd build
        ./login < ./test/commands.txt
